### ISSUE TITLE
Is this webservice now available?

### ISSUE THREAD

**Issue by maelle** [edwardcapriolo/clavin-aas#1]
Hi, what are your plans regarding the web service?

I'd like to use CLAVIN from the statistics software R (see https://github.com/ropensci/unconf16/issues/8) / add CLAVIN as a R package and using a web service might be the right solution. :smile:

**Comment by edwardcapriolo** [comment]
This solution works. You build your clavin lucence as normal and deploy the web application. There is no R client but the web service should be easy to get at from any language. If you build an R client I do not mind adding it to the project

**Comment by maelle** [comment]
Ok, thanks. There is no already built website hosted somewhere? I see there is http://clavin.berico.us/clavin-web/

**Comment by edwardcapriolo** [comment]
Right no unfortunately I do not have the $$$ to stand up a free service ATM :) Should i launch a kickstarter?

**Comment by maelle** [comment]
Ok I see. I've opened a new issue elsewhere and tagged you. There must be an elegant solution somehow. :-)
